Development
ialiev685/goit-markup-hw-02 pull request #1
Opened 2020-12-18 22:07 UTC by ialiev685

Домашняя работа №2 выполнена, прошу проверить.

2020-12-20 11:05 UTC, magom001 requested changes
Опционально: посмотри, какие еще значения в стилях повторяются много раз, вынеси их в переменные и попробуй сделать так, чтобы не повторять эти стили в отдельно взятых селекторах (может быть эти стили можно сделать глобальными?)

2020-12-20 11:05 UTC, magom001 commented on css/style.css
> +  background-color: #f5f4fa;
в переменную

2020-12-20 11:05 UTC, magom001 commented on css/style.css
> +  background-color: #2f303a;
в переменную

2020-12-20 11:05 UTC, magom001 commented on css/style.css
> +  color: rgba(255, 255, 255, 0.6);
в переменную

2020-12-20 11:05 UTC, magom001 commented on portfolio.html
> +          ><br />
br не надо. Позиционирование делается с помощью css

2020-12-20 13:47 UTC, ialiev685 commented on css/style.css
> +  --first-color-text: #212121;
К сожалению на субботнем вебинаре не удалось присутствовать. Запись еще не скинули, обязательно хотел посмотреть.

2020-12-21 06:45 UTC, magom001 commented on css/style.css
> +  --color-text-white: var(--color-white);
подсказка: это лучше назвать `--color-text-inverse`. Если будешь делать темную тему для сайта, то у тебя основной цвет текста будет белый, а обратный - черный

2020-12-21 15:56 UTC, magom001 approved these changes
по замечаниям поправь и сойдет

2020-12-21 15:56 UTC, magom001 commented on css/style.css
> +/*первый основной основной цвет текста #212121*/
info: комментарии уже не нужны. Более того они имеют свойство разъезжаться с реальностью, потому что их никто не обновляет.

2020-12-21 15:56 UTC, magom001 commented on css/style.css
> +.caption {
пустой блок, УДАЛИТЬ!

2020-12-21 15:56 UTC, magom001 commented on css/style.css
> +.without-dot {
👍🏻

2020-12-21 15:56 UTC, magom001 commented on css/style.css
> +.footer address {
пустой блок, удали!

2020-12-23 18:05 UTC, merged